'use client';

import { useState, useRef, useEffect } from 'react';

const SUGGESTIONS = [
  'Which category has the best gross margin?',
  'What is the main financial risk right now?',
  'How is Beer performing vs last year?',
  'Compare Wine and Spirits profitability',
  'Is the personnel cost under control?',
  'How is Food trending in 2025?'
];

export default function Chat() {
  const [messages, setMessages] = useState([
    {
      role: 'assistant',
      content:
        "Hi — I'm the CashFlow365 AI Controller. I can answer questions across Beer, Food, Wine, Spirits, and Personnel Cost using your real 2023–2025 figures. Try one of the questions below, or ask your own."
    }
  ]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const chatRef = useRef(null);

  useEffect(() => {
    if (chatRef.current) chatRef.current.scrollTop = chatRef.current.scrollHeight;
  }, [messages, loading]);

  async function send(customQ) {
    const q = customQ || input.trim();
    if (!q || loading) return;

    const nextMessages = [...messages, { role: 'user', content: q }];
    setMessages(nextMessages);
    setInput('');
    setLoading(true);

    try {
      const res = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ messages: nextMessages })
      });
      const data = await res.json();

      if (!res.ok) {
        setMessages((m) => [...m, { role: 'error', content: data.error || 'Something went wrong.' }]);
      } else {
        setMessages((m) => [...m, { role: 'assistant', content: data.reply }]);
      }
    } catch (err) {
      setMessages((m) => [
        ...m,
        { role: 'error', content: 'Network error — check the deployment and Azure environment variables.' }
      ]);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div style={styles.app}>
      <header style={styles.header}>
        <div style={styles.brand}>
          <div style={styles.dot} />
          <h1 style={styles.h1}>CashFlow365 — AI Controller</h1>
        </div>
        <div style={styles.status}>
          <span style={styles.pulse} /> Live · Azure OpenAI (gpt-4o)
        </div>
      </header>

      <div style={styles.modules}>
        <Badge label="Beer" bg="#C9A227" fg="#1a1400" />
        <Badge label="Food" bg="#166534" />
        <Badge label="Wine" bg="#922B4E" />
        <Badge label="Spirits" bg="#7C3AED" />
        <Badge label="Personnel Cost" bg="#1D4ED8" />
      </div>

      <div style={styles.chat} ref={chatRef}>
        {messages.map((m, i) => (
          <Message key={i} role={m.role} content={m.content} />
        ))}
        {loading && (
          <div style={styles.typing}>
            <span style={styles.dotAnim} />
            <span style={{ ...styles.dotAnim, animationDelay: '0.2s' }} />
            <span style={{ ...styles.dotAnim, animationDelay: '0.4s' }} />
          </div>
        )}
      </div>

      <div style={styles.chips}>
        {SUGGESTIONS.map((s) => (
          <div key={s} style={styles.chip} onClick={() => send(s)}>
            {s}
          </div>
        ))}
      </div>

      <div style={styles.inputbar}>
        <input
          style={styles.input}
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && send()}
          placeholder="Ask about any category, month, or trend..."
        />
        <button style={styles.button} disabled={loading} onClick={() => send()}>
          Send
        </button>
      </div>
      <div style={styles.note}>
        Live — answers are generated by Azure OpenAI (gpt-4o), grounded in the real financial data stored in this app.
      </div>
    </div>
  );
}

function Badge({ label, bg, fg }) {
  return (
    <span style={{ ...styles.badge, background: bg, color: fg || '#fff' }}>{label}</span>
  );
}

function Message({ role, content }) {
  if (role === 'user') {
    return <div style={styles.msgUser}>{content}</div>;
  }
  if (role === 'error') {
    return <div style={styles.msgError}>Error: {content}</div>;
  }
  return (
    <div style={styles.msgAi}>
      <span style={styles.tag}>AI CONTROLLER</span>
      <div style={{ whiteSpace: 'pre-wrap' }}>{content}</div>
    </div>
  );
}

const styles = {
  app: {
    maxWidth: 900,
    margin: '0 auto',
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    background: '#fff',
    boxShadow: '0 0 40px rgba(11,31,58,0.08)',
    fontFamily: "'Segoe UI', Georgia, sans-serif",
    color: '#0B1F3A'
  },
  header: {
    background: 'linear-gradient(135deg, #0B1F3A 0%, #0F2A4A 100%)',
    color: '#fff',
    padding: '22px 28px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between'
  },
  brand: { display: 'flex', alignItems: 'center', gap: 12 },
  dot: { width: 12, height: 12, borderRadius: '50%', background: '#059669', boxShadow: '0 0 8px #059669' },
  h1: { fontSize: 19, margin: 0, fontWeight: 600, letterSpacing: 0.3 },
  status: {
    fontSize: 12,
    background: 'rgba(5,150,105,0.18)',
    color: '#6ee7b7',
    padding: '5px 12px',
    borderRadius: 20,
    border: '1px solid rgba(110,231,183,0.35)',
    display: 'flex',
    alignItems: 'center',
    gap: 6
  },
  pulse: { width: 7, height: 7, borderRadius: '50%', background: '#6ee7b7' },
  modules: {
    display: 'flex',
    gap: 8,
    padding: '14px 28px',
    background: '#F8FAFC',
    borderBottom: '1px solid #E5E9F0',
    flexWrap: 'wrap'
  },
  badge: { fontSize: 11, fontWeight: 600, padding: '5px 11px', borderRadius: 14, letterSpacing: 0.3 },
  chat: {
    flex: 1,
    padding: '24px 28px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    background: '#FBFCFE',
    minHeight: 320
  },
  msgUser: {
    alignSelf: 'flex-end',
    maxWidth: '78%',
    padding: '14px 16px',
    borderRadius: 14,
    background: '#0B1F3A',
    color: '#fff',
    borderBottomRightRadius: 4,
    fontSize: 14.5,
    lineHeight: 1.55
  },
  msgAi: {
    alignSelf: 'flex-start',
    maxWidth: '78%',
    padding: '14px 16px',
    borderRadius: 14,
    background: '#fff',
    border: '1px solid #E5E9F0',
    borderBottomLeftRadius: 4,
    fontSize: 14.5,
    lineHeight: 1.55,
    boxShadow: '0 1px 3px rgba(11,31,58,0.06)'
  },
  msgError: {
    alignSelf: 'flex-start',
    maxWidth: '78%',
    padding: '14px 16px',
    borderRadius: 14,
    background: '#FEF2F2',
    border: '1px solid #FCA5A5',
    color: '#7f1d1d',
    fontSize: 14.5
  },
  tag: {
    display: 'inline-block',
    fontSize: 10.5,
    fontWeight: 700,
    color: '#0F766E',
    background: '#ECFDF5',
    borderRadius: 6,
    padding: '2px 7px',
    marginBottom: 8,
    letterSpacing: 0.4
  },
  chips: { display: 'flex', flexWrap: 'wrap', gap: 8, padding: '0 28px 14px', background: '#FBFCFE' },
  chip: {
    fontSize: 12.5,
    padding: '8px 13px',
    borderRadius: 18,
    border: '1px solid #CBD5E1',
    background: '#fff',
    color: '#0B1F3A',
    cursor: 'pointer',
    fontWeight: 500
  },
  inputbar: {
    display: 'flex',
    gap: 10,
    padding: '16px 28px 22px',
    borderTop: '1px solid #E5E9F0',
    background: '#fff'
  },
  input: {
    flex: 1,
    padding: '12px 16px',
    borderRadius: 24,
    border: '1px solid #CBD5E1',
    fontSize: 14,
    outline: 'none'
  },
  button: {
    background: '#0F766E',
    color: '#fff',
    border: 'none',
    padding: '0 22px',
    borderRadius: 24,
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: 14
  },
  typing: { alignSelf: 'flex-start', display: 'flex', gap: 4, padding: '14px 16px' },
  dotAnim: { width: 6, height: 6, borderRadius: '50%', background: '#94a3b8' },
  note: { fontSize: 11, color: '#5b6b7f', textAlign: 'center', padding: '8px 0 0' }
};
