'use client';

import { useState, useRef, useEffect } from 'react';
import { useRouter } from 'next/navigation';

const SUGGESTIONS = [
  'Which category has the best gross margin?',
  'What is the main financial risk right now?',
  'How is Beer performing vs last year?',
  'Compare Wine and Spirits profitability',
  'Is the personnel cost under control?',
  'How is Food trending in 2025?'
];

export default function Chat() {
  const router = useRouter();
  const [messages, setMessages] = useState([
    {
      role: 'assistant',
      content:
        "Hi — I'm the CashFlow365 AI Controller. I can answer questions across Beer, Food, Wine, Spirits, and Personnel Cost using your real 2023–2025 figures. Try one of the questions below, or ask your own."
    }
  ]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const chatRef = useRef(null);

  useEffect(() => {
    if (chatRef.current) chatRef.current.scrollTop = chatRef.current.scrollHeight;
  }, [messages, loading]);

  async function send(customQ) {
    const q = customQ || input.trim();
    if (!q || loading) return;

    const nextMessages = [...messages, { role: 'user', content: q }];
    setMessages(nextMessages);
    setInput('');
    setLoading(true);

    try {
      const res = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ messages: nextMessages })
      });
      const data = await res.json();

      if (!res.ok) {
        setMessages((m) => [...m, { role: 'error', content: data.error || 'Something went wrong.' }]);
      } else {
        setMessages((m) => [...m, { role: 'assistant', content: data.reply }]);
      }
    } catch (err) {
      setMessages((m) => [
        ...m,
        { role: 'error', content: 'Network error — check the deployment and Azure environment variables.' }
      ]);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div style={styles.page}>
      <div style={styles.app}>
        <header style={styles.header}>
          <div style={styles.brand}>
            <div style={styles.logoMark}>
              <div style={styles.dot} className="pulse-dot" />
            </div>
            <div>
              <h1 style={styles.h1}>CashFlow365</h1>
              <div style={styles.h1sub}>AI Controller</div>
            </div>
          </div>
          <div style={styles.headerRight}>
            <div style={styles.status}>
              <span style={styles.pulse} /> Live · Azure OpenAI (gpt-4o)
            </div>
            <button
              className="ghost-btn"
              style={styles.logoutBtn}
              onClick={() => router.push('/login')}
            >
              Log out
            </button>
          </div>
        </header>

        <div style={styles.modules}>
          <Badge label="Beer" bg="#C9A227" fg="#1a1400" />
          <Badge label="Food" bg="#166534" />
          <Badge label="Wine" bg="#922B4E" />
          <Badge label="Spirits" bg="#7C3AED" />
          <Badge label="Personnel Cost" bg="#1D4ED8" />
        </div>

        <div style={styles.chat} ref={chatRef}>
          {messages.map((m, i) => (
            <Message key={i} role={m.role} content={m.content} />
          ))}
          {loading && (
            <div style={styles.typingRow} className="msg-in">
              <Avatar role="assistant" />
              <div style={styles.typing}>
                <span style={styles.dotAnim} className="dot-anim" />
                <span style={{ ...styles.dotAnim, animationDelay: '0.2s' }} className="dot-anim" />
                <span style={{ ...styles.dotAnim, animationDelay: '0.4s' }} className="dot-anim" />
              </div>
            </div>
          )}
        </div>

        <div style={styles.chips}>
          {SUGGESTIONS.map((s) => (
            <div key={s} className="chip-btn" style={styles.chip} onClick={() => send(s)}>
              {s}
            </div>
          ))}
        </div>

        <div style={styles.inputbar}>
          <input
            className="chat-input"
            style={styles.input}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && send()}
            placeholder="Ask about any category, month, or trend..."
          />
          <button className="send-btn" style={styles.button} disabled={loading} onClick={() => send()}>
            Send
          </button>
        </div>
        <div style={styles.note}>
          Live — answers are generated by Azure OpenAI (gpt-4o), grounded in the real financial data stored in this app.
        </div>
      </div>
    </div>
  );
}

function Badge({ label, bg, fg }) {
  return (
    <span style={{ ...styles.badge, background: bg, color: fg || '#fff' }}>{label}</span>
  );
}

function Avatar({ role }) {
  if (role === 'user') {
    return <div style={styles.avatarUser}>U</div>;
  }
  return <div style={styles.avatarAi}>AI</div>;
}

function Message({ role, content }) {
  if (role === 'user') {
    return (
      <div style={styles.rowUser} className="msg-in">
        <div style={styles.msgUser}>{content}</div>
        <Avatar role="user" />
      </div>
    );
  }
  if (role === 'error') {
    return (
      <div style={styles.rowAi} className="msg-in">
        <Avatar role="assistant" />
        <div style={styles.msgError}>Error: {content}</div>
      </div>
    );
  }
  return (
    <div style={styles.rowAi} className="msg-in">
      <Avatar role="assistant" />
      <div style={styles.msgAi}>
        <span style={styles.tag}>AI CONTROLLER</span>
        <div style={{ whiteSpace: 'pre-wrap' }}>{content}</div>
      </div>
    </div>
  );
}

const styles = {
  page: {
    minHeight: '100vh',
    background: 'linear-gradient(180deg, #eef1f6 0%, #e4e9f1 100%)',
    padding: '0 0 40px'
  },
  app: {
    maxWidth: 900,
    margin: '0 auto',
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    background: '#fff',
    boxShadow: '0 12px 50px rgba(11,31,58,0.12)',
    fontFamily: "'Segoe UI', Georgia, sans-serif",
    color: '#0B1F3A'
  },
  header: {
    background: 'linear-gradient(135deg, #0B1F3A 0%, #123a63 55%, #0F2A4A 100%)',
    color: '#fff',
    padding: '22px 28px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    flexWrap: 'wrap'
  },
  brand: { display: 'flex', alignItems: 'center', gap: 12 },
  logoMark: {
    width: 38,
    height: 38,
    borderRadius: 11,
    background: 'rgba(255,255,255,0.08)',
    border: '1px solid rgba(255,255,255,0.14)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center'
  },
  dot: { width: 12, height: 12, borderRadius: '50%', background: '#059669', boxShadow: '0 0 8px #059669' },
  h1: { fontSize: 18, margin: 0, fontWeight: 700, letterSpacing: 0.3, lineHeight: 1.2 },
  h1sub: { fontSize: 11.5, color: '#9fb3cc', fontWeight: 500, letterSpacing: 0.4, marginTop: 1 },
  headerRight: { display: 'flex', alignItems: 'center', gap: 10 },
  status: {
    fontSize: 12,
    background: 'rgba(5,150,105,0.18)',
    color: '#6ee7b7',
    padding: '5px 12px',
    borderRadius: 20,
    border: '1px solid rgba(110,231,183,0.35)',
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    whiteSpace: 'nowrap'
  },
  pulse: { width: 7, height: 7, borderRadius: '50%', background: '#6ee7b7' },
  logoutBtn: {
    fontSize: 12,
    fontWeight: 600,
    color: '#e2e8f0',
    background: 'rgba(255,255,255,0.06)',
    border: '1px solid rgba(255,255,255,0.18)',
    borderRadius: 20,
    padding: '6px 14px',
    cursor: 'pointer'
  },
  modules: {
    display: 'flex',
    gap: 8,
    padding: '14px 28px',
    background: '#F8FAFC',
    borderBottom: '1px solid #E5E9F0',
    flexWrap: 'wrap'
  },
  badge: { fontSize: 11, fontWeight: 600, padding: '5px 11px', borderRadius: 14, letterSpacing: 0.3 },
  chat: {
    flex: 1,
    padding: '24px 28px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 18,
    background: '#FBFCFE',
    minHeight: 320
  },
  rowUser: { display: 'flex', alignItems: 'flex-end', gap: 10, alignSelf: 'flex-end', maxWidth: '82%' },
  rowAi: { display: 'flex', alignItems: 'flex-end', gap: 10, alignSelf: 'flex-start', maxWidth: '82%' },
  avatarUser: {
    width: 30,
    height: 30,
    borderRadius: '50%',
    background: '#0B1F3A',
    color: '#fff',
    fontSize: 11,
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0
  },
  avatarAi: {
    width: 30,
    height: 30,
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #0F766E, #0d9488)',
    color: '#fff',
    fontSize: 10.5,
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0
  },
  msgUser: {
    padding: '14px 16px',
    borderRadius: 14,
    background: '#0B1F3A',
    color: '#fff',
    borderBottomRightRadius: 4,
    fontSize: 14.5,
    lineHeight: 1.55
  },
  msgAi: {
    padding: '14px 16px',
    borderRadius: 14,
    background: '#fff',
    border: '1px solid #E5E9F0',
    borderBottomLeftRadius: 4,
    fontSize: 14.5,
    lineHeight: 1.55,
    boxShadow: '0 1px 3px rgba(11,31,58,0.06)'
  },
  msgError: {
    padding: '14px 16px',
    borderRadius: 14,
    background: '#FEF2F2',
    border: '1px solid #FCA5A5',
    color: '#7f1d1d',
    fontSize: 14.5,
    borderBottomLeftRadius: 4
  },
  tag: {
    display: 'inline-block',
    fontSize: 10.5,
    fontWeight: 700,
    color: '#0F766E',
    background: '#ECFDF5',
    borderRadius: 6,
    padding: '2px 7px',
    marginBottom: 8,
    letterSpacing: 0.4
  },
  chips: { display: 'flex', flexWrap: 'wrap', gap: 8, padding: '0 28px 14px', background: '#FBFCFE' },
  chip: {
    fontSize: 12.5,
    padding: '8px 13px',
    borderRadius: 18,
    border: '1px solid #CBD5E1',
    background: '#fff',
    color: '#0B1F3A',
    cursor: 'pointer',
    fontWeight: 500
  },
  inputbar: {
    display: 'flex',
    gap: 10,
    padding: '16px 28px 22px',
    borderTop: '1px solid #E5E9F0',
    background: '#fff'
  },
  input: {
    flex: 1,
    padding: '12px 16px',
    borderRadius: 24,
    border: '1px solid #CBD5E1',
    fontSize: 14,
    outline: 'none'
  },
  button: {
    background: 'linear-gradient(135deg, #0F766E 0%, #0d9488 100%)',
    color: '#fff',
    border: 'none',
    padding: '0 22px',
    borderRadius: 24,
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: 14
  },
  typingRow: { display: 'flex', alignItems: 'flex-end', gap: 10, alignSelf: 'flex-start' },
  typing: {
    display: 'flex',
    gap: 4,
    padding: '14px 16px',
    background: '#fff',
    border: '1px solid #E5E9F0',
    borderRadius: 14,
    borderBottomLeftRadius: 4
  },
  dotAnim: { width: 6, height: 6, borderRadius: '50%', background: '#94a3b8' },
  note: { fontSize: 11, color: '#5b6b7f', textAlign: 'center', padding: '8px 0 0' }
};
